//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graduate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Theme_cons
    {
        public System.Guid Id { get; set; } = Guid.NewGuid();
        public System.Guid Theme { get; set; }
        public System.Guid Matrial { get; set; }
        public System.Guid Owner { get; set; } = App.user;
    
        public virtual Materials Materials { get; set; }
        public virtual Teachers Teachers { get; set; }
        public virtual Themes Themes { get; set; }
    }
}
